package com.kixyu9527.kixyubook.core.reader.engine

import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Compatibility fixtures that mirror publisher structures, not only files generated by the app. */
class EpubCompatibilityContractTest {
    @get:Rule val folder = TemporaryFolder()

    @Test fun epub2NcxNavigationAndNestedDirectoriesRemainReadable() = runBlocking {
        val epub = folder.newFile("epub2-ncx.epub")
        ZipOutputStream(epub.outputStream()).use { zip ->
            zip.text("mimetype", "application/epub+zip")
            zip.text(
                "META-INF/container.xml",
                """<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf"/></rootfiles></container>""",
            )
            zip.text(
                "OEBPS/content.opf",
                """<package xmlns="http://www.idpf.org/2007/opf" version="2.0"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>EPUB 2 测试</dc:title></metadata><manifest><item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/><item id="c1" href="Text/c1.xhtml" media-type="application/xhtml+xml"/><item id="c2" href="Text/c2.xhtml" media-type="application/xhtml+xml"/></manifest><spine toc="ncx"><itemref idref="c1"/><itemref idref="c2"/></spine></package>""",
            )
            zip.text(
                "OEBPS/toc.ncx",
                """<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><navMap><navPoint id="volume"><navLabel><text>第一卷</text></navLabel><content src="Text/c1.xhtml"/><navPoint id="chapter"><navLabel><text>第一章</text></navLabel><content src="Text/c1.xhtml#start"/></navPoint></navPoint><navPoint id="second"><navLabel><text>第二章</text></navLabel><content src="Text/c2.xhtml"/></navPoint></navMap></ncx>""",
            )
            zip.text("OEBPS/Text/c1.xhtml", """<html xmlns="http://www.w3.org/1999/xhtml"><body><h1>第一章</h1><p id="start">正文一。</p></body></html>""")
            zip.text("OEBPS/Text/c2.xhtml", """<html xmlns="http://www.w3.org/1999/xhtml"><body><h1>第二章</h1><p>正文二。</p></body></html>""")
        }

        val parser = EpubBookParser()
        val outlines = parser.readChapterOutlines(epub)
        val second = parser.readChapter(epub, 1)

        assertEquals(listOf("第一卷", "第二章"), outlines.map(DocumentChapterOutline::title))
        assertEquals("正文二。", second?.paragraphs?.single())
    }

    @Test fun domBudgetsAreFallbackSignalsRatherThanBookAcceptanceLimits() = runBlocking {
        val epub = folder.newFile("large-manifest.epub")
        ZipOutputStream(epub.outputStream()).use { zip ->
            zip.text("mimetype", "application/epub+zip")
            zip.text(
                "META-INF/container.xml",
                """<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OPS/book.opf"/></rootfiles></container>""",
            )
            val decorativeItems = buildString {
                repeat(20_001) { append("<item id=\"asset$it\" href=\"asset$it.bin\" media-type=\"application/octet-stream\"/>") }
            }
            zip.text(
                "OPS/book.opf",
                """<package xmlns="http://www.idpf.org/2007/opf"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>大清单</dc:title></metadata><manifest>$decorativeItems<item id="chapter" href="chapter.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="chapter"/></spine></package>""",
            )
            zip.text("OPS/chapter.xhtml", """<html xmlns="http://www.w3.org/1999/xhtml"><body><p>仍然可以阅读。</p></body></html>""")
        }

        val parser = EpubBookParser()
        assertEquals("大清单", parser.readMetadata(epub, epub.name).title)
        assertTrue(parser.readChapter(epub, 0)?.paragraphs?.contains("仍然可以阅读。") == true)
    }
}

private fun ZipOutputStream.text(path: String, value: String) {
    putNextEntry(ZipEntry(path))
    write(value.toByteArray())
    closeEntry()
}
